Notes
========================================================
## Journal of International Money and Finance 
[Risk off periods]()
[Bank flow](http://www.sciencedirect.com/science?_ob=GatewayURL&_method=citationSearch&_urlVersion=4&_origin=SDVIALERTHTML&_version=1&_piikey=S0261-5606%2815%2900003-0&md5=19502d2bbf16206efd0a0bfd49607716).  The main finding is that even though the effect of a common factor has increased since 2000, the main determinants are largely heterogenous suggesting that desirabel policy may differ for different countries. Domestic factors are those like government debt, country risk and macroeconomic fundamentals. The standard way to look at this involves descibing the global and regional common factors as *push factors* and the country specific factors as *pull factors*. If push factors are more important, global regulation should concentrate on te adoption of liquidty ring-fences; if pull factors are more important, there is less reason to be concerned about propogation of financial shocks. About 40\% to 50\% of the shocks appear to be global. Some countries are mostly affected by global factors, others are mostly affected by local factors. Calvo (1996) initiated the research in this area.  There is a lot of literature that assesses the flow of funds wtih the VIX index. Bruno and Shin (2015) construct a model of global banking that explains how the risk sentiments of global banks affect the international credit flows. 

[Bruno and Shin, Capital Flows, Cross-broder banking and global liquidity](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.296.5090&rep=rep1&type=pdf), builds on the general equilibrium framework of Geanakopolos (1997, 2009) and Fostel and Geanokopolos (2008, 2012). Gorton (2007, 2009)  and Gorton and Metrick (2010) have shed light on the modern bank run where increased collateral requirements ("haircuts") reduce the capacity to borrow. This model combines the procyclicaity of leverage with the interaction between global and local banks. This has already been documented by Cetorelli and Goldberg (2009, 2010). Forbes and Warnock (2011) find that the VIX can explain international capital flows.  This is explained by the VIX being a mirror of banks VaR. 

The model deals with the interaction between global banks with access to internationl money markets and domestic banks. The cost of funds will increase flow from global to local. 

The transmission of financial conditons across borders is often referred to as *global liquidity*.  When global banks apply more lenient conditions on local banks, more lenient credit conditions are transferred to the local economy. This framework suggests that global liquidity can be measured by aggregate cross boarder lending through the banking system. 



## Banks capital flows and financial crisis
[Fed paper on capital flows](http://www.federalreserve.gov/econresdata/ifdp/2014/files/ifdp1121.pdf).  Important that models be able to capture the non-linear nature of financial crisis. Important is the role of financial intermediation. this model has banks with occasional leverage constraints.  There are occasional constraints as well as regular business cycles. Agency issues can retrict bank ability to borrow in the short-term debt market.  There is empirical evidece that rapid credit expansion is frequently financed by overseas borrowing. See Mendoza and Terrones (2012) and Bruno and Shinn (2012). Other papers looking at the cycle of boom and bust with credit are Gournichas and Obstfeld (2012) and Schularick and Taylor (2012). Bianchi (2010), Mendoza (2010), Bianchi and Mendoza (2013), Benigno (2012) and Schmitt-Grohe and Uribe (2011) have Nonlinear Stochastic Dynamic General Equilibrium models that switch between normal times and crisis. Most of these models impose exogenous collateral constraints. Here there is an endogenous agency problem.  

## India
India was one of the countries that was most affected by the *tapering talk*.  There is more here on [Vox EU](http://www.voxeu.org/article/impact-fed-s-exit-india).  There is a link to Eichengreen and Gupta (2014) that assesses the effect of the tapering on exchange rates, reserves and equity prices. 


## A new taxonomy of sudden stops
Notes from *A New Taxonomy of sudden stops* it is in [Citulike](http://www.citeulike.org/pdf//user/RobHayward/article/13405794/990575/1-s20-S0261560614001600-main.pdf?expires=1414145894&hash=BAF93D382E369D1392457F86A39BD1DAA4CCF0BA).  It distringuishes between gross and net flows. 1980s there was interest in *Starts in Gross Capital Outflows*.  Amongst the writers are Cuddington (1986) and Dooley (1986). In the 1990s attention turned to *Sudden Stops*.  This looked at an abrupt reversal of net flows. These were associated with current account and real exchange rate adjustment that had a major effect on output. Calvo (1998), Calvo, Izquiredo and Mejia (2004) and (2008) and Guidotti Struzenegger and Villar (2004) and Calvallo and Frenkel (2008). Now attention has turned back to gross flows and the relationship between gross and net flows. Cowan and De Gregorio (2007), Calderon and Kubota (2013), Rothenberg and Warnock (2011), Forbes and Warnock (2012) and Alberola, Erce and Serena (2012) look at the role of Gross flows in determining Sudden Stops. These papers argue that Sudden Stops may be driven by external and country ideosyncratic features and by the difference in the behaviour of domestic and external residents. Powell, Ratha and Mohapatra (2002) argue that Gross Outflows and Inflows are strongly associated and that they may Granger-cause each other causing viscious and virtuous cycles between capital flows and macroeconomic variables. 

The aim is to propose a taxonomy of Sudden Stops by exploring the simultaneous roles of gross inflows, gross outflows and net flows.

Borio and Disyatat (2011) have a useful discussion of role of international banks and banking flows.  However, Bruno and Shin 2012a and 2012b have emphasises the potential disruption that can be caused by changes in gross flows even if there is no net effect. THere is a report from the Committee on International Economic Policy Research (2012) that assesses the potential disruption that can be caused by debt-creating cross-border flows (i.e. banking flow) during period of forced de-leverage. 

A Sudden Stop can be defined as a fall in net inflows (say relative to trend as in Calvo and Majia (2004) or gross flows (such as a fall in gross inflows or an increase in gross outflows as in Forbes and Warnock (2012). 

The definition here is from Calvo and Majia (2004) where the sudden stop is defined as the flow falls below one standard deviation of its historical mean (conditional on its subsequent fall to 2 standard deviations below the mean).  Here the algorithm is applied to each series. The effect of the Sudden Stop on the GDP and the RER (10 quarters before and 10 quarters after) is assessed. 

The main finding is that the effect on GDP Is most intense when there are sudden stops to SSION (gross inflows, gross outflow and net flows) and SSIN (Gross inflow and net).  SSO (Gross out), SSON (Gross out and net) and SSN (net flows) are not statistically significant. ** Important**

SSI requires a substantial sale of domestic assets by non-residnets; SSO requires a substantial purchase of overseas assets by residents. The former is likely to affect the liquiity and leverage of domestic households and firms. The latter may be fuelled by overseas opportunities as much as domestic concerns. 

Are bank flows more disruptive than pure portoflio flows?  They may lead to forced deleveraging. The capital flows are broken down into sub-type. The flows can be categorised as either *direct*, *portfolio* or *other*.  The *other* are part of the bank flow. Therefore there is DIR (direct investment in reporting economy), PIL (portfolio investment in liabilities) and OIR (other investment in liabilities); DIA (direct investment abroad), PIA (portfolio investment abroad) and OIA (other investment abroad). 

> "It stands out from the table that the episodes associated with changes in "other investment" - both assets (OIA, liasbilities (OIL) and net (OIN) -- account for the largest share of all episodes across all types of Sudden Stops"
(p.23)
>

## Mixture model
These are from Wikipedia [http://en.wikipedia.org/wiki/Mixture_model](Mixture Model).  Probabilistic model where there are subpopulations. This is based on a mixture distribution. There are N random variables that relate to a distribution with K components. The mixture weights sum to one. There are K sets of parameters specificying the distribution (such as mean and variance for a normal distribution). The mixture weights are the same as the *factor loadings* (see [http://en.wikipedia.org/wiki/Factor_analysis](Wikipdeia on factor analysis) ).  There may be something in that to answer the question about how many regimes to choose. 

These are some notes from the Economic Systems Journal [http://www.sciencedirect.com/science/journal/09393625/38/1](http://www.sciencedirect.com/science/journal/09393625/38/1)

This is a symbosium on challenges to financial stability in central and eastern Europe. There is focus on the importance of credit growth. The importance of foreign currency loans was central to CEE. Fidrmuc, Crespo Cuaresma and Hake analyse 21 studies and find that supply factors are the most important. 

[Paper](http://ac.els-cdn.com/S0939362513000927/1-s2.0-S0939362513000927-main.pdf?_tid=54dbb99e-380e-11e4-87bd-00000aab0f6c&acdnat=1410259673_0c2494e7ae3d46030151b2ff8755c2af)
Egert and Kocenda show how the exchange rate affects capital flows.  GARCH model shows that exchange rates of CEE are sensitive to macroeconomic news. Crisis influences the currencies.  They react more to the central bank in the crisis.  

